# Generated by Django 4.2.6 on 2023-10-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateField(verbose_name='data published')),
                ('likes_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateField(verbose_name='data published')),
                ('likes_num', models.IntegerField(default=0)),
            ],
        ),
    ]
